name: Intersmash - Build and run tests on openshift sandbox

on: [push]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v3

      - name: Set up Maven
        uses: stCarolas/setup-maven@v4.5
        with:
          maven-version: 3.8.7

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'

      - name: Build with Maven
        run: mvn -version ; mvn clean install --batch-mode -fae -DskipTests

      - name: Oc login
        run: |
          oc login ${{ secrets.OPENSHIFT_SERVER }} --token=${{ secrets.OPENSHIFT_TOKEN }}

      - name: Test with Maven
        run: mvn test --batch-mode -fae -pl testsuite -DfailIfNoTests=false -Dxtf.openshift.namespace=$(oc project -q) -Dxtf.bm.namespace=$(oc project -q) -Dxtf.openshift.url=${{ secrets.OPENSHIFT_SERVER }} -Dxtf.openshift.admin.username=$(oc whoami) -Dxtf.openshift.admin.token='${{ secrets.OPENSHIFT_TOKEN }}' -Dxtf.openshift.master.username=$(oc whoami) -Dxtf.openshift.master.token='${{ secrets.OPENSHIFT_TOKEN }}'
