name: Intersmash - Build and run tests on openshift sandbox

on: [push]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v3

      - name: Set up Maven
        uses: stCarolas/setup-maven@v4.5
        with:
          maven-version: 3.8.7

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'

      - name: Build with Maven
        run: mvn clean install -U -B -DskipTests

      - name: oc login
        run: |
          oc login ${{ secrets.OPENSHIFT_SERVER }} --token=${{ secrets.OPENSHIFT_TOKEN }}

      - name: Test with Maven
        run: |
          export OC_NAMESPACE=$(oc project -q)
          export OC_USERNAME=$(oc whoami)
          mvn test -U -B -pl testsuite -DfailIfNoTests=false -Dxtf.openshift.namespace=$OC_NAMESPACE -Dxtf.bm.namespace=$OC_NAMESPACE -Dxtf.openshift.url=${{ secrets.OPENSHIFT_SERVER }} -Dxtf.openshift.admin.username=$OC_USERNAME -Dxtf.openshift.admin.token='${{ secrets.OPENSHIFT_TOKEN }}' -Dxtf.openshift.master.username=$OC_USERNAME -Dxtf.openshift.master.token='${{ secrets.OPENSHIFT_TOKEN }}'

      - name: Archive test results
        uses: actions/upload-artifact@v3
        with:
          name: code-coverage-report
          path: '**/target/surefire-reports'